name: Export PNG favicons

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install converter
        run: |
          python -m pip install --upgrade pip
          python -m pip install cairosvg
      - name: Export PNG variants
        run: |
          cairosvg logo-mark.svg -o favicon-32.png -W 32 -H 32
          cairosvg logo-mark.svg -o favicon-16.png -W 16 -H 16
          cairosvg logo-mark.svg -o apple-touch-icon.png -W 180 -H 180
      - name: Commit PNGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add favicon-32.png favicon-16.png apple-touch-icon.png || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: export PNG favicons from SVG"
            git push
          else
            echo "No PNG changes to commit"
          fi

